name: tor
services:
  server:
    image: casjaysdevdocker/tor:latest
    container_name: tor
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    privileged: true
    environment:
      - TOR_DNS_ENABLED=yes
      - TOR_RELAY_ENABLED=yes
      - TOR_HIDDEN_ENABLED =yes
      - TOR_BRIDGE_ENABLED=yes
      - TOR_SOCKS_SAFE=0
      - TOR_SOCKS_TIMEOUT=30
      - TOR_OR_PORT=8444
      - TOR_PT_PORT=8445
      - TOR_DIR_PORT=8440
      - TOR_NICK_NAME=CasjaysDev
      - TOR_ADMIN=tor-admin@${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '8118:8118/tcp'
      - '8440:8440/tcp'
      - '8444:8444/tcp'
      - '8445:8445/tcp'
      - '9040:9040/tcp'
      - '9050:9050/tcp'
      - '9051:9051/tcp'
      - '9053:9053/tcp'
      - '9053:9053/udp'
    volumes:
      - /var/lib/srv/${USER}/docker/casjaysdevdocker/tor/latest/data:/data
      - /var/lib/srv/${USER}/docker/casjaysdevdocker/tor/latest/config:/config
    networks:
      - tor

networks:
  tor:
    name: tor
    external: false
